width = float(input("What is the wdith?"))
hight = float(input("What is the hight?"))
base = float(input("What is the size of the base?"))
print(f"the area is {width*hight}, the volume is {width*base*hight}")
input()
